Migrating from Dubclub
whopio/api-docs pull request #12
Opened 2023-03-29 21:44 UTC by henryk89

2023-03-29 22:30 UTC, gwkline requested changes

2023-03-29 22:30 UTC, gwkline commented on src/pages/dubclub.mdx
This doesn't really say anything about the actual migration. Can they bring their existing customers over? If yes, explain how. If not, explain that and tell why (similar to the Patreon guide)

2023-03-29 22:44 UTC, stevo2105 commented
#### 📝 Changed routes:


| [**/dubclub**](https://new-documentation-mdq9driab-whop.vercel.app/dubclub) |
|:-:|
|<a href="https://new-documentation-mdq9driab-whop.vercel.app/dubclub"><img src="https://images.weserv.nl?url=https://sjc.microlink.io/v73slsdnqElNeQxqnkDwWZ2OsUEkbAH-5VPLOm6PQiA352ZAP10PGAVNnegyjWj2MJD9rX5Yz2S2n5oFlS_cTw.png&w=600" alt="Screenshot of /dubclub" width="300"></a><br /><sup><a href="https://images.weserv.nl?url=https://sjc.microlink.io/uGDKaoGewQ7WOmIfDvPwsLlovhjhF-SDy7H7fMbb7qhA11j7proetp3Gr-2O_D7uktGyy-T9YswStiPd7Mzgng.png">(view full size)</a> |







Commit 68b856272f444454126f8dc5decde719080fe9bb (https://new-documentation-mdq9driab-whop.vercel.app).

2023-03-30 01:01 UTC, gwkline approved these changes

2023-03-31 14:51 UTC, jacc commented on src/pages/dubclub.mdx
> +Wanting to sell Sports picks with the best tools and the lowest fees on the marketplace? With Dubclub charging 18% fees compared to Whop's 3% fees, the fees alone are more than enough reason to switc
Wording here is very clunky - potentially `With Dubclub charging 18% vs. Whop's 3%, the fees alone are worth the switch`.

2023-03-31 14:51 UTC, jacc commented on src/pages/dubclub.mdx
> +Now that you have signed up for your Whop account, you must announce to your current customers that you’re changing your primary point of sale. We highly recommend you post in your Discord/platform,
i have no idea how Dubclub works but maybe make this announcement more clear - ex. card only, no PayPal currently, etc.

2023-03-31 14:51 UTC, jacc commented on src/pages/dubclub.mdx
> +Now that you have signed up for your Whop account, you must announce to your current customers that you’re changing your primary point of sale. We highly recommend you post in your Discord/platform,
typo with `promo'code`

2023-03-31 14:51 UTC, jacc commented on src/pages/dubclub.mdx
> +Whop is a platform similar to Dubclub. However, they have cheaper fees and many more features - you can now leave written reviews, become an affiliate & get paid for referring friends!
good highlight of the consumer facing features but needs better wording - ex: `Whop is similar [...] they also make it easier to write reviews and reward YOU with a native affiliate program`

2023-03-31 14:51 UTC, jacc commented on src/pages/dubclub.mdx
> +We will also be featured on their marketplace, which we are super excited about, and their infrastructure enables us to sell more than just Discord roles - including courses, software, and more!
these should be two different points - maybe include featured in the point above?

drop the line about infrastructure and make it more "customer facing" - ex, "whop also will allow us to include more than just Discord access - we can also include courses, software, and more with your subscription on their platform!"

2023-04-07 06:15 UTC, jacc approved these changes

2023-04-07 06:15 UTC, merged