Document scoped API keys
whopio/api-docs pull request #9
Opened 2023-03-23 02:21 UTC by jacc

- Add scoped API key documentation
- Calendly link

2023-03-24 14:02 UTC, stevo2105 commented
#### 📝 Changed routes:


| [**/software-intro**](https://new-documentation-b3p2s1hr9-whop.vercel.app/software-intro) |
|:-:|
|<a href="https://new-documentation-b3p2s1hr9-whop.vercel.app/software-intro"><img src="https://images.weserv.nl?url=https://sjc.microlink.io/uOm24bUEgJ4B_LzOgCV7upBidPwRMEENhWKDgRzcZXO9EA4WPwPDGE7aa4uT079RkvvsCLNRVdg5gNbD0MRGgg.png&w=600" alt="Screenshot of /software-intro" width="300"></a><br /><sup><a href="https://images.weserv.nl?url=https://sjc.microlink.io/eT4fovVER2W3mP32YrIT_0jUsrxVkrWASYah0tpJHJnBw8Yvow7foc6JAtnZlu78k1ImzT_B0fjBWxcka-P3hg.png">(view full size)</a> |







Commit ecd7d5fbad33afff51fe3ede128c29394d6a224a (https://new-documentation-b3p2s1hr9-whop.vercel.app).

2023-03-24 15:00 UTC, gwkline requested changes

2023-03-24 15:00 UTC, gwkline commented on src/pages/api-keys.mdx
> +Scoped API keys are **the only way** for your company to use client-sided keys.
```suggestion
Scoped API keys are **the best way** for your company to use client-sided keys.
```

2023-03-24 15:00 UTC, gwkline commented on src/pages/api-keys.mdx
> +For more authentication help, [our developer documentation page on authentication](https://dev.whop.com/reference/authentication) can provide some more technical specifics.
```suggestion
For more authentication help, [our API reference page on authentication](https://dev.whop.com/reference/authentication) can provide some more technical specifics.
```

2023-03-24 15:00 UTC, gwkline commented on src/pages/api-keys.mdx
> +3. Add the permissions you want this key to have access to
```suggestion
3. Add the permissions you want this key to have access to. If you are storing keys client-side, we recommend keeping your permissions as minimal as possible. 
```

2023-03-24 15:00 UTC, gwkline commented on src/pages/api-keys.mdx
> +API keys are an essential tool for accessing and integrating with Whop's API. An API key is a unique identifier that allows a software product to access Whop's API and validate licenses, retrieve use
```suggestion
API keys are an essential tool for accessing and integrating with Whop's API. An API key is a unique identifier that allows a developer to access Whop's API on behalf of a company and validate licenses, retrieve user information, and more.
```

2023-03-24 15:00 UTC, gwkline commented on src/pages/api-keys.mdx
> +  It's important that you keep your API keys safe and secure - unless otherwise
It's important that you keep your API keys safe and secure - if not properly scoped, your API keys can be dangerous if they fall into the wrong hands.

2023-03-25 18:06 UTC, gwkline approved these changes

2023-03-25 18:06 UTC, merged